const FULL_NODES_PEER = '4001';
const FIRST_WALLET_SPV = '4002';
const SECOND_WALLET_SPV = '4003';
const MEM_POOL_FILE = 'mem-pool.js';
const ERROR_MESSAGE = 'Error: ';
const EXIT_MESSAGE = 'Bye bye';
const ERROR_RATE = 0.04;
const DIFFICULTY = 4;
const MINING_REWARD = 10;
const INITIAL_WALLET_VALUE = 100;
const TRANSACTION_REWARD = 1;
const MAX_TRANSACTIONS_IN_BLOCK = 4;
const MAX_INTERVAL_TIME = 1500;
const MIN_INTERVAL_TIME = 800;

module.exports = {
    FULL_NODES_PEER,
    FIRST_WALLET_SPV,
    SECOND_WALLET_SPV,
    MEM_POOL_FILE,
    ERROR_MESSAGE,
    EXIT_MESSAGE,
    ERROR_RATE,
    DIFFICULTY, 
    MINING_REWARD, 
    INITIAL_WALLET_VALUE,
    TRANSACTION_REWARD,
    MAX_TRANSACTIONS_IN_BLOCK,
    MAX_INTERVAL_TIME,
    MIN_INTERVAL_TIME
};