const ERROR_RATE = 0.04;
const DIFFICULTY = 4;
const MINING_REWARD = 10;
const INITIAL_WALLET_VALUE = 100;
const TRANSACTION_REWARD = 1;
const MAX_INTERVAL_TIME = 1000;
const MIN_INTERVAL_TIME = 500;

module.exports = {
    ERROR_RATE,
    DIFFICULTY, 
    MINING_REWARD, 
    INITIAL_WALLET_VALUE,
    TRANSACTION_REWARD,
    MAX_INTERVAL_TIME,
    MIN_INTERVAL_TIME
};